server:
  port: 8080

spring:
  datasource:
    url: jdbc:sqlite:watering.sqlite
    driverClassName: org.sqlite.JDBC
#  jpa:
#    database-platform: that.custom.SQLiteDialect
logging:
  level:
    root: info